"""Hand-curated content for the UML diagrams: method roles and extension points.

Everything structural (modules, functions, Config fields, spec folders) is read
from the code by build_uml_diagrams.py. This file holds only what the code
cannot tell you:

ROLES       which functions are the README's STANDARD / ALTERNATIVE / naive
            (shown-for-bias) methods, so the diagram colours them.
EXTENSIONS  where a new model or module would plug in, and what it is for.

Extension tuple: (lane, stereotype, name, signature, use, pairs_with)
lane        new | data | methods | checks | spec  -> the column it sits under
stereotype  model | alternative | loader | check | spec | module
pairs_with  related template (tNN) or glossary entry (gNN), "" if none
"""

ROLES = {
    "t00": {
        "S": ["collapse_versions_latest", "member_months_daily", "service_category_claim",
              "net_pharmacy_drop_pairs"],
        "A": ["collapse_versions_net", "member_months_midmonth", "service_category_line",
              "net_pharmacy_signed"],
    },
    "t01": {
        "S": ["rate_ci_poisson_exact", "readmissions_per_index", "readmission_rate", "trend_rolling12"],
        "A": ["rate_ci_cluster_bootstrap", "readmissions_per_1000", "trend_yoy_same_month"],
    },
    "t02": {"S": ["score_published_weights"], "A": ["score_empirical_weights"]},
    "t03": {
        "S": ["fit_logistic", "odds_ratios", "tiers_by_capacity"],
        "A": ["fit_gradient_boosting", "segments_kmeans"],
    },
    "t04": {
        "S": ["ci_wilson", "evaluate_measure", "rate_summary"],
        "A": ["ci_jeffreys", "hybrid_rate", "systematic_sample"],
    },
    "t05": {
        "S": ["pmpm_ratio_of_sums", "truncate_percentile", "decompose_additive", "mlr_regulatory",
              "build_episodes_nonoverlap"],
        "A": ["pmpm_mean_of_members", "truncate_fixed_attachment", "decompose_log", "mlr_simple",
              "build_episodes_overlap"],
    },
    "t06": {
        "S": ["match_propensity", "did_pmpm"],
        "A": ["bootstrap_did", "two_part_did"],
        "N": ["naive_pre_post"],
    },
    "t07": {
        "S": ["shared_savings_core", "reconcile_shared_savings", "reconcile_subcap",
              "reconcile_fee_upside", "scenario_grid"],
        "A": ["monte_carlo_shared_savings", "msr_for_confidence"],
    },
    "t08": {
        "S": ["chain_ladder", "forecast_sarimax"],
        "A": ["bornhuetter_ferguson", "forecast_ets"],
    },
    "t09": {
        "S": ["power_two_proportions", "power_two_means", "design_effect", "cluster_sample_size",
              "stratified_block_randomize"],
        "A": ["simulate_power", "sim_two_proportions", "sim_cluster_proportions", "sim_cost_did"],
    },
    "t10": {
        "S": ["did_twfe", "event_study", "psm_att", "smd_table"],
        "A": ["its_segmented", "ipw", "aipw_ate"],
        "N": ["naive_post_comparison", "naive_difference"],
    },
    "t11": {
        "S": ["km_table", "logrank", "cox_ph", "ph_test"],
        "A": ["cox_statsmodels", "discrete_time_hazard", "rmst_difference", "cox_time_varying"],
        "N": ["naive_event_share", "cox_naive_ever_exposed"],
    },
    "t12": {
        "S": ["mixed_model_effect", "responder_analysis", "arm_mean_change"],
        "A": ["ancova_change", "gee_effect"],
    },
    "t13": {
        "S": ["risk_model", "oe_table", "funnel_limits", "funnel_flags", "eb_shrink_oe"],
        "A": ["mixed_logistic_ratios", "eb_beta_binomial"],
    },
    "t14": {
        "S": ["metric_table_sql", "experiment_readout"],
        "A": ["metric_table_pandas", "cuped_effect"],
    },
    "t15": {
        "S": ["funnel", "time_to_start", "km_curve", "pa_metrics"],
        "A": ["cohort_conversion", "denial_pareto"],
        "N": ["naive_median_days"],
    },
}

EXTENSIONS = {
    "t00": [
        ("methods", "model", "MemberAttribution", "attribute_pcp(claims, enrollment, lookback_months)",
         "Plurality-of-E&M PCP assignment; the member->provider link that TCOC, VBC and provider profiling all need.",
         "t05, t07, t13, g09"),
        ("methods", "model", "ClinicalGrouper", "ccsr_category(dx_cd) / drg_family(drg_cd)",
         "Condition-level reporting (CCSR, DRG families) on top of service categories.", "t01, t05"),
        ("methods", "model", "EnrollmentSpans", "enrollment_spans(enrollment, max_gap_days)",
         "Collapse monthly rows into spans with allowable gaps; basis for continuous enrollment and churn.",
         "g04, g26"),
        ("data", "loader", "IngestAdapters", "load_x12_837(path) / load_fhir_eob(bundle)",
         "Read real payer feeds (837 claims, FHIR EOB) into the same claim schema the generator emits.",
         "g01, g02"),
        ("data", "loader", "ProviderDirectory", "load_nppes(path)",
         "NPPES taxonomy, specialty and group/TIN roll-ups for provider dimensions.", "t13"),
        ("checks", "check", "VendorOnboardingChecks", "check_duplicate_lines / check_member_xwalk",
         "Extra data-quality gates when a new data vendor or payer feed arrives.", ""),
    ],
    "t01": [
        ("methods", "model", "AvoidableEDClassifier", "nyu_ed_classify(claims)",
         "Split ED visits into emergent / non-emergent / primary-care-treatable to target ED diversion.", "g06"),
        ("methods", "model", "PlannedReadmissionFilter", "exclude_planned(index_stays, procedures)",
         "Drop planned readmissions (CMS algorithm) so rates match HRRP-style definitions.", "t13"),
        ("methods", "alternative", "NegBinomialRateModel", "rate_negbin(events, exposure, covariates)",
         "Overdispersed counts with covariate adjustment: a third CI option beside Poisson and bootstrap.", ""),
        ("methods", "model", "RiskAdjustedUtilization", "oe_utilization(events, risk_score)",
         "Observed/expected visits per 1,000 so groups with different acuity compare fairly.", "t02"),
        ("methods", "model", "UtilizationAnomalyDetector", "control_chart(monthly, sigma)",
         "Shewhart / STL control limits that flag monthly spikes for operations teams.", ""),
        ("methods", "model", "PreventableAdmissions", "pqi_rates(stays, member_months)",
         "AHRQ PQI / ambulatory-care-sensitive admission rates.", "g07"),
    ],
    "t02": [
        ("methods", "model", "InteractionTerms", "build_interactions(X, version)",
         "Disease x disease and payment-HCC-count variables to complete the V24/V28 specification.", ""),
        ("methods", "model", "SegmentModels", "score_segment(X, segment)",
         "Community / institutional / new-enrollee / ESRD segment coefficients.", ""),
        ("methods", "alternative", "HHS_HCC_Variant", "score_hhs_hcc(X, metal_level)",
         "ACA commercial risk-transfer model (concurrent, metal-level) as a third scoring option.", ""),
        ("methods", "model", "MLSuspectingModel", "predict_suspect_hcc(features)",
         "Gradient-boosted probability an HCC is present but undocumented; prioritises chart review beyond rule-based suspect_gaps.",
         "t03"),
        ("methods", "model", "RevenueProjection", "project_revenue(score, county_rate, months)",
         "Turn RAF lift into a Finance revenue forecast.", "t05"),
        ("checks", "check", "RADVAuditSampler", "radv_sample / extrapolate_error",
         "Audit sampling and payment-error extrapolation to size RADV exposure.", "g24"),
        ("spec", "spec", "ReferenceTables", "reference/<model>_*.csv",
         "Drop in another model year's dx map, coefficients and hierarchies; methods read by version.", ""),
    ],
    "t03": [
        ("methods", "model", "ExplainabilityLayer", "shap_values(model, X)",
         "Member-level top drivers so care managers see why someone is high risk.", ""),
        ("methods", "model", "ImpactabilityModel", "fit_uplift_t_learner(X, y, treated)",
         "Rank members by who benefits from outreach, not just who is sickest.", "t06, t10"),
        ("methods", "alternative", "TimeToEventRisk", "fit_cox_risk(df, covariates)",
         "Predict when, not just whether: risk of admission within N days.", "t11"),
        ("checks", "check", "FairnessAudit", "check_subgroup_calibration(y, p, group)",
         "Calibration and capture rate by race, sex, LOB before deployment.", "g29"),
        ("checks", "check", "DriftMonitor", "check_psi(train_scores, live_scores)",
         "Population-stability index on scores and features between scoring runs.", "g28"),
        ("new", "module", "persistence.py", "save_model(model, path) / model_card(...)",
         "Version, persist and document models for a monthly production scoring cadence.", ""),
    ],
    "t04": [
        ("spec", "spec", "NewMeasureSpecs", "measures/FAKE_CBP.yaml, FAKE_COL.yaml ...",
         "Add measures with zero code: the engine is spec-driven (denominator, numerator, exclusions).", ""),
        ("methods", "model", "ExclusionEngine", "apply_exclusions(member_level, events, rules)",
         "Hospice, palliative care, frailty + advanced illness exclusions shared across measures.", ""),
        ("methods", "model", "StarsComposite", "star_rating(rates, cut_points, weights)",
         "MA Star / QRS forecast: measure stars, weighted summary rating, distance to next cut point.", "t13"),
        ("methods", "model", "GapClosurePropensity", "closure_likelihood(gaps, history)",
         "Score each open gap by likelihood to close so outreach goes where it moves the rate.", "t03"),
        ("methods", "model", "EquityStratification", "stratified_rates(member_level, by)",
         "Rates by race/ethnicity and SES with small-cell suppression (HEDIS stratification).", "g30"),
        ("data", "loader", "SupplementalDataLoader", "load_lab_feed(path) / load_ccda(path)",
         "Standard and non-standard supplemental data (labs, EHR) feeding the numerator.", "g02"),
    ],
    "t05": [
        ("methods", "model", "RiskAdjustedPMPM", "pmpm_risk_adjusted(pmpm, raf)",
         "Divide by average risk score so LOBs, practices or years compare fairly.", "t02"),
        ("methods", "model", "CredibilityBlend", "credibility_pmpm(own, manual, member_months)",
         "Blend small-group experience with a manual rate (limited-fluctuation / Buhlmann).", "g22"),
        ("methods", "model", "StopLossRecovery", "stoploss_recovery(member_cost, attach, agg_attach)",
         "Specific and aggregate stop-loss recoveries; net cost after reinsurance.", "g23"),
        ("methods", "model", "EpisodeTargetPrice", "episode_target_price(episodes, benchmark)",
         "BPCI-A style target prices and episode savings on top of build_episodes_*.", "t07"),
        ("methods", "alternative", "TrendProjection", "project_trend(pmpm, months)",
         "Forward PMPM trend from completed history for budgets.", "t08"),
        ("data", "loader", "PriceTransparencyRates", "load_mrf_rates(path)",
         "Transparency-in-coverage negotiated rates to benchmark unit cost against market.", ""),
    ],
    "t06": [
        ("methods", "alternative", "StaggeredAdoptionDiD", "did_staggered(panel, cohort_col)",
         "Callaway-Sant'Anna style DiD when members enrol in the program at different months.", "t10"),
        ("methods", "alternative", "DoublyRobustDiD", "dr_did(matched, covariates)",
         "Outcome model + propensity weights; protects against covariate-dependent trends.", "t10"),
        ("methods", "alternative", "SyntheticControl", "synthetic_control(panel, treated_unit)",
         "One or few treated units (a single clinic or region).", "g13"),
        ("methods", "model", "DoseResponse", "did_by_engagement(matched, dose_col)",
         "Show savings rising with engagement level: supports causal story to Finance.", ""),
        ("methods", "model", "CostEffectiveness", "icer(costs, qalys) / markov_cea(...)",
         "Cost per QALY when the value story is clinical, not just dollar savings.", "g18"),
        ("methods", "model", "BudgetImpact", "budget_impact(uptake, cost_offset, years)",
         "Multi-year payer budget impact of scaling the program.", "g19"),
    ],
    "t07": [
        ("spec", "spec", "NewContractYAML", "contracts/aco_reach.yaml, ma_full_risk.yaml ...",
         "Model new deals with no code: tracks, MSR/MLR, corridors, quality gates are contract fields.", ""),
        ("methods", "model", "RiskAdjustedBenchmark", "benchmark_with_raf(bench, raf_base, raf_perf, cap)",
         "MSSP-style risk-score adjustment and caps on benchmark growth.", "t02"),
        ("methods", "model", "QualityGateFromMeasures", "quality_score_from_rates(rates, gates)",
         "Compute the quality multiplier from actual measure rates instead of a fixed input.", "t04"),
        ("methods", "model", "AttributionChurnSim", "simulate_attribution_churn(members, churn_rate)",
         "Benchmark and savings volatility caused by attribution turnover.", "t00"),
        ("methods", "model", "TrackSelection", "choose_track(contracts, risk_tolerance)",
         "Compare tracks/contracts on expected value vs downside percentile from Monte Carlo.", ""),
        ("new", "module", "accruals.py", "settlement_schedule(result, true_up_months)",
         "Cash-flow timing and Finance accruals for interim and final settlements.", ""),
    ],
    "t08": [
        ("methods", "model", "MackChainLadder", "mack_se(cum)",
         "Standard error of IBNR so reserves carry a range, not a point.", ""),
        ("methods", "alternative", "BootstrapODP", "bootstrap_odp(tri, n_sims)",
         "Full predictive distribution of reserves (over-dispersed Poisson bootstrap).", ""),
        ("methods", "model", "SegmentedTriangles", "complete_by(claims, exposure, group_col)",
         "Separate lag patterns for IP / OP / professional / Rx, then sum.", ""),
        ("methods", "alternative", "ExogenousForecast", "forecast_gbm(pmpm, drivers)",
         "Forecast with drivers (membership mix, benefit changes, unit-cost contracts).", ""),
        ("methods", "model", "HierarchicalReconciliation", "reconcile_forecasts(by_lob, total)",
         "Make LOB forecasts add to the enterprise total.", ""),
        ("checks", "check", "BacktestBiasCheck", "check_backtest_bias(errors, tol)",
         "Alert when completed estimates are consistently high or low.", ""),
    ],
    "t09": [
        ("methods", "model", "NonInferiorityPower", "power_noninferiority(p, margin, alpha)",
         "Guardrail studies: show the program does no harm within a margin.", "t14"),
        ("methods", "alternative", "SteppedWedge", "sim_stepped_wedge(clusters, steps, icc)",
         "Staggered clinic rollout where every site eventually gets the program.", "t10"),
        ("methods", "model", "SurvivalPower", "events_needed_logrank(hr, alpha, power)",
         "Schoenfeld events-needed for time-to-event endpoints.", "t11"),
        ("methods", "model", "GroupSequential", "obrien_fleming_bounds(looks, alpha)",
         "Interim looks with alpha spending.", ""),
        ("methods", "model", "BayesianAssurance", "assurance(prior, n_per_arm)",
         "Probability of success averaging over uncertainty in the effect size.", ""),
        ("spec", "spec", "SAPTemplates", "sap_*.md",
         "Additional statistical-analysis-plan templates (cluster, non-inferiority, pragmatic).", ""),
    ],
    "t10": [
        ("methods", "alternative", "StaggeredDiD", "did_callaway_santanna(panel, cohort_col)",
         "Practices adopting at different months: TWFE is biased with heterogeneous effects.", "t06"),
        ("methods", "alternative", "SyntheticControl", "synthetic_control(panel, treated_unit)",
         "One treated unit (a state or health system) with many donors.", "g13"),
        ("methods", "alternative", "RegressionDiscontinuity", "rdd(df, running, cutoff)",
         "Eligibility set by a risk-score threshold.", "g14"),
        ("methods", "alternative", "InstrumentalVariables", "iv_2sls(df, instrument)",
         "Unmeasured confounding with a credible instrument (distance, provider preference).", "g15"),
        ("methods", "model", "HeterogeneousEffects", "cate_dr_learner(df, covariates)",
         "Which subgroups benefit: conditional average treatment effects.", "t03"),
        ("methods", "model", "SensitivityAnalysis", "e_value(rr) / rosenbaum_bounds(...)",
         "How strong an unmeasured confounder would need to be to explain the effect away.", ""),
    ],
    "t11": [
        ("methods", "alternative", "CompetingRisks", "aalen_johansen(df) / fine_gray(df)",
         "Death competes with readmission: KM overstates cumulative incidence.", "g16"),
        ("methods", "model", "RecurrentEvents", "andersen_gill(df, covariates)",
         "Multiple readmissions per member.", "t01"),
        ("methods", "alternative", "ParametricAFT", "weibull_aft(df, covariates)",
         "Extrapolate beyond follow-up (needed for cost-effectiveness models).", "g18"),
        ("methods", "model", "MultiStateModel", "multistate(df, transitions)",
         "Home -> hospital -> SNF -> death pathways.", ""),
        ("methods", "alternative", "LandmarkAnalysis", "landmark(df, t_landmark)",
         "Simpler alternative to time-varying exposure when the program starts after index.", ""),
        ("methods", "model", "RandomSurvivalForest", "fit_rsf(df, covariates)",
         "Individual survival predictions with non-linear effects.", "t03"),
    ],
    "t12": [
        ("spec", "spec", "NewInstrumentSpecs", "instruments/promis10.yaml, gad7.yaml ...",
         "Add instruments with no code: items, reverse-scoring, bands, MCID, licence.", ""),
        ("methods", "model", "IRTScoring", "score_irt(items, item_params)",
         "Graded-response-model T-scores (PROMIS CAT / short forms).", ""),
        ("methods", "alternative", "MultipleImputation", "mice_impute(wide, m)",
         "MAR imputation for ANCOVA / responder analyses.", "g17"),
        ("methods", "model", "TippingPoint", "delta_adjusted_mi(wide, deltas)",
         "MNAR sensitivity: how bad dropouts must be to erase the effect.", ""),
        ("methods", "model", "AnchorBasedMCID", "anchor_mcid(change, anchor)",
         "Derive the responder threshold from a global-impression anchor.", ""),
        ("checks", "check", "PsychometricChecks", "check_test_retest(icc) / check_cfa_fit(...)",
         "Validate a new or translated instrument before using it as an endpoint.", ""),
    ],
    "t13": [
        ("methods", "model", "MultiMeasureComposite", "composite_score(measures, weights)",
         "Roll readmission, mortality, cost into one profile score with reliability weights.", "t04"),
        ("methods", "model", "CostEfficiencyOE", "oe_cost(patients, covariates)",
         "Gamma GLM expected cost: efficiency profiling next to quality.", "t05"),
        ("methods", "alternative", "BayesianHierarchical", "hierarchical_ratio(patients, provider)",
         "Full posterior per provider (PyMC / Stan).", ""),
        ("methods", "model", "RankUncertainty", "rank_intervals(posterior_draws)",
         "League tables with rank intervals instead of a single rank.", ""),
        ("methods", "model", "PeerGroupBenchmarks", "benchmark_percentile(value, ref, peer_group)",
         "Compare within specialty / bed size / teaching status.", ""),
        ("checks", "check", "SmallCellSuppression", "check_publishable(oe, min_cases)",
         "Suppress or pool before external release.", "g30"),
    ],
    "t14": [
        ("spec", "spec", "NewMetricsYAML", "metrics.yaml: ratio, retention, funnel metrics",
         "New metrics with no code; SQL and pandas engines both read the YAML.", ""),
        ("spec", "spec", "NewDbtModels", "models/stg_*.sql, mart_*.sql",
         "New staging / mart models; dbt_lite resolves ref() order automatically.", ""),
        ("methods", "alternative", "SequentialTesting", "msprt_readout(df, spec)",
         "Always-valid p-values when stakeholders peek at results daily.", "t09"),
        ("methods", "alternative", "CUPAC", "cupac_effect(df, y, predicted_pre)",
         "ML-predicted pre-period covariate for more variance reduction than CUPED.", ""),
        ("methods", "model", "SegmentReadout", "readout_by_segment(df, spec, segments)",
         "Effects by segment with multiplicity correction.", ""),
        ("new", "module", "dbt_lite.py +", "run_freshness(con, sources) / snapshot_scd2(...)",
         "Source freshness tests and SCD2 snapshots in the dbt-lite runner.", ""),
    ],
    "t15": [
        ("methods", "model", "StaffingQueueModel", "erlang_c(arrivals, handle_time, target)",
         "Reviewers needed to hit 72-hour / 7-day PA decision targets.", ""),
        ("methods", "model", "AutoApprovalModel", "predict_approval(features)",
         "Gold-carding: which requests can be auto-approved safely.", "t03"),
        ("methods", "model", "ProcessMining", "variant_paths(event_log)",
         "Find rework loops and bottlenecks between lifecycle stages.", ""),
        ("methods", "alternative", "VolumeForecast", "forecast_requests(daily, horizon)",
         "Forecast PA volume for staffing and SLA planning.", "t08"),
        ("methods", "model", "PublicReportingMetrics", "public_pa_report(pa, year)",
         "CMS-0057-F annual public metrics (approval, denial, overturn, turnaround).", ""),
        ("checks", "check", "AppealQualityCheck", "check_overturn_by_reason(pa)",
         "Reasons with high overturn rates point at bad denial criteria.", ""),
    ],
}

# Toolkit-level: new templates that would extend the portfolio.
NEW_TEMPLATES = [
    ("t16_pharmacy_adherence_specialty", "PDC/MPR adherence, specialty-drug trend, biosimilar switching",
     "g10, g12"),
    ("t17_sdoh_geospatial", "ADI/SVI linkage, drive-time access, network adequacy", ""),
    ("t18_clinical_nlp", "Note-based phenotypes, negation, HCC evidence extraction", "g31"),
    ("t19_fraud_waste_abuse", "Outlier billing, peer-comparison anomaly models", "t13"),
    ("t20_member_churn_engagement", "Disenrollment prediction and retention ROI", "g26"),
]
